library(tidyverse)
load('rda/murders.rda')

murders %>% 
  mutate(abb = reorder(abb, rate)) %>% 
  ggplot(aes(abb, rate)) +
  geom_bar(width = .5, stat = 'identity', color = 'black') +
  coord_flip()

# save a plot generated by ggplot2 to a dir called "figs"
ggsave("figs/barplot.png") # this is the relative path to the current working directory
